### ISSUE TITLE
ImportError: cannot import name 'object_detector' from 'tflite_model_maker' 

### ISSUE THREAD

**Issue by moezeus** [googlecodelabs/odml-pathways#1]
## Expected Behavior
normal output (no error)

## Actual Behavior
ImportError: cannot import name 'object_detector' from 'tflite_model_maker' (/usr/local/lib/python3.7/dist-packages/tflite_model_maker/__init__.py)

## Steps to Reproduce the Problem

1. use the tutorial at : https://colab.research.google.com/github/googlecodelabs/odml-pathways/blob/main/object-detection/codelab2/python/Train_a_salad_detector_with_TFLite_Model_Maker.ipynb
2. run cell Perequisites --> "Import the required packages." 
3. if using "!pip install -q tflite-model-maker-nightly"or "!pip install -q tflite-model-maker" will end on this error : ImportError: cannot import name 'configs' from 'tflite_model_maker'
4. but if using "!pip install  tflite-model-maker" will produce error: ImportError: cannot import name 'object_detector' from 'tflite_model_maker' (/usr/local/lib/python3.7/dist-packages/tflite_model_maker/__init__.py)

## Specifications
Python 3.7 google colab
- Version: 0.2.5
- Platform: Google Colab Python 3.7

Any help would be very appreciated !

**Comment by khanhlvg** [comment]
Thanks for the report. The issue has been fixed. Please try again.
