### ISSUE TITLE
model export is taking forever and sometimes using full RAM resulting in crashing..

### ISSUE THREAD

**Issue by ManoharSai2000** [googlecodelabs/odml-pathways#4]
## Expected Behavior
model.export() should give a tflite file output.

## Actual Behavior
It is taking forever to run, and sometimes it crashes.

## Steps to Reproduce the Problem

1. Run the notebook but with effcient det lite 4 version.

## Specifications

- Version: Colab up to date
- Platform: Colab

## Update:
It took 4.5 hrs for converting the model!. 
But again the evaluate_tflite is only evaluating on part of the test set and stopping!

![image](https://user-images.githubusercontent.com/45100887/120161253-b95dd180-c214-11eb-92ec-5b1452dc3ff9.png)

**Comment by khanhlvg** [comment]
This seems to be the resource limitation of the free Colab. I couldn't reproduce the issue on Colab Pro's High-RAM version. Please try again using a machine with higher specs (either Colab Pro, or use GCP's VM, or your local machine)
