### ISSUE TITLE
Link to "Get Started with Image classification" pathway in section 1 is incorrect

### ISSUE THREAD

**Issue by sidgrover21** [googlecodelabs/odml-pathways#7]
## Expected Behavior
In the codelab "Build your first computer vision app on android or iOS".Section 1 there is a link to the pathway of the codelab called "Get Started with Image Classification". This link should take the user to a list of image classification codelabs imho.

## Actual Behavior
That link is incorrect and doesnt lead anywhere.

## Steps to Reproduce the Problem

1. Go to codelab https://codelabs.developers.google.com/tflite-computer-vision-mobile#0
2. In section 1 click on the link  "Get Started with Image Classification"

## Specifications

Using Google Chrome v93.0 if that matters

**Comment by khanhlvg** [comment]
Thanks for the report. We'll get it fix soon.

**Comment by khanhlvg** [comment]
The link is fixed.
https://codelabs.developers.google.com/tflite-computer-vision-mobile#0
